"""Flat-bottomed delta wedge reference geometry (GVWD §4.6).

A delta-planform vehicle with:
  - Triangular planform (apex at front, base at rear half-width b = y_tip)
  - Single inclined lower plane at angle theta_d to freestream
  - Single horizontal upper plane through the apex
  - Trailing edge: rectangular or triangular base cross-section

The leading edges are straight rays from the apex to the wingtips and
must lie on the design-Mach planar shock for the geometry to be a true
"waverider"; the swept-shock attachment condition

    M_n,LE = M_design * cos(Lambda) > 1

is checked at construction.

Inputs:
    M_design : design Mach
    theta_d  : lower-plane inclination [rad]
    Lambda   : LE sweep from spanwise axis [rad]
    L        : body length [m]
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Optional

import numpy as np

from gvwd.geometry.mesh import Mesh
from gvwd.thermo.oblique_shock import (
    obtain_beta, swept_oblique_shock, ShockDetachedError,
)


@dataclass
class FlatDelta:
    """Flat-bottomed delta-planform reference geometry.

    Mesh structure:
        4 vertices (apex, wingtip+, wingtip-, base centerline below).
        triangles: upper (1), lower (1), base (2).

    The base is a triangle (centerline drop) connecting the lower
    centerline at z = -L tan(theta_d) to the wingtip LE points at z = 0;
    so it is NOT degenerate but is closed.
    """

    M_design: float
    theta_d: float           # rad, lower-plane wedge angle
    Lambda: float            # rad, LE sweep
    L: float = 10.0
    gamma: float = 1.4

    mesh: Optional[Mesh] = field(default=None, init=False, repr=False)
    y_tip: float = field(default=0.0, init=False)
    z_TE_centerline: float = field(default=0.0, init=False)
    swept_shock: Optional[dict] = field(default=None, init=False, repr=False)
    beta_body: float = field(default=0.0, init=False)

    def __post_init__(self) -> None:
        if not (0.0 < self.Lambda < math.pi / 2):
            raise ValueError(f"Lambda must be in (0, pi/2)")
        if self.theta_d <= 0.0:
            raise ValueError(f"theta_d must be positive")

        # Two-stage shock validity check:
        #   (1) LE attachment: the LE itself rides on the swept shock,
        #       which requires M_perp = M cos(Lambda) > 1.
        #   (2) Body-frame attached oblique shock at the standard 2-D
        #       wedge: this is the shock generated by the lower surface
        #       and used for surface Cp. Must satisfy theta_d <
        #       theta_max(M_design).
        # If (2) fails the geometry is unphysical at this Mach.
        M_perp = self.M_design * math.cos(self.Lambda)
        if M_perp <= 1.0:
            raise ShockDetachedError(
                f"LE detached: M cos(Lambda) = {M_perp:.3f} <= 1 "
                f"(M={self.M_design}, Lambda={math.degrees(self.Lambda):.2f})"
            )
        # Body-frame attached oblique shock for surface Cp
        from gvwd.thermo.oblique_shock import obtain_beta
        try:
            self.beta_body = obtain_beta(self.theta_d, self.M_design,
                                          self.gamma)
        except ShockDetachedError as e:
            raise ShockDetachedError(
                f"flat-delta surface shock detached: {e}")
        # Cache the swept-shock dict for downstream use (panel method, etc.)
        # and for diagnostics. ``swept_shock`` is the LE-perpendicular-plane
        # value, NOT the body-frame surface-pressure shock.
        try:
            self.swept_shock = swept_oblique_shock(
                self.theta_d, self.M_design, self.Lambda, self.gamma
            )
        except ShockDetachedError:
            # Body frame is attached even if perpendicular-frame is
            # detached (very-swept / high-LE-sweep cases). Mark None.
            self.swept_shock = None
        self._build()

    def _build(self) -> None:
        tan_L = math.tan(self.Lambda)
        tan_th = math.tan(self.theta_d)
        self.y_tip = self.L / tan_L
        self.z_TE_centerline = -self.L * tan_th

        # 4 vertices
        A   = np.array([0.0, 0.0, 0.0])                          # apex
        Wp  = np.array([self.L, +self.y_tip, 0.0])               # upper wingtip+
        Wm  = np.array([self.L, -self.y_tip, 0.0])               # upper wingtip-
        CB  = np.array([self.L, 0.0, self.z_TE_centerline])      # lower centerline base
        vertices = np.array([A, Wp, Wm, CB])

        # Faces (outward normals via right-hand rule)
        faces = np.array([
            [0, 2, 1],     # upper triangular plane (z = 0), normal +z
            [0, 1, 3],     # lower y>0 panel (apex - Wp - CB), normal -z and -y
            [0, 3, 2],     # lower y<0 panel (apex - CB - Wm), normal -z and +y
            [3, 1, 2],     # base triangle (CB - Wp - Wm), normal +x
        ])
        labels = np.array(["upper", "lower_right", "lower_left", "base"],
                            dtype=object)
        self.mesh = Mesh(vertices, faces, labels, metadata={
            "kind": "flat_delta",
            "M_design": self.M_design,
            "theta_d_deg": math.degrees(self.theta_d),
            "Lambda_deg": math.degrees(self.Lambda),
            "L": self.L,
            "y_tip": self.y_tip,
            "beta_body_deg": math.degrees(self.beta_body),
            "M_perp": self.M_design * math.cos(self.Lambda),
        })

    @property
    def theta_d_deg(self) -> float:
        return math.degrees(self.theta_d)

    @property
    def Lambda_deg(self) -> float:
        return math.degrees(self.Lambda)
